version: "3.7"
services:
  #Laravel Service
  app:
    container_name: curr_rate_app
    restart: always
    tty: true
    working_dir: /var/www/app

    build:
      context: .
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: "idekey=IDE_DEBUG"
      PHP_IDE_CONFIG: "serverName=curr_rate_app"
    #    ports:
    #      - 9001:9000
    #      - 9002:9001
    volumes:
      - .:/var/www/app
    depends_on:
      - database
    links:
      - database
    networks:
      - curr_rate_network

  #DB Service
  database:
    image: postgres:10.4
    container_name: curr_rate_database
    restart: always
    tty: true
    environment:
      - POSTGRES_DB=curr_rate
      - POSTGRES_USER=curr_rate
      - POSTGRES_PASSWORD=curr_rate
    ports:
      - 5432:5432
    networks:
      - curr_rate_network

  #Nginx Service
  server:
    image: nginx:alpine
    container_name: curr_rate_server
    restart: always
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/var/www/app
      - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
    networks:
      - curr_rate_network

#Docker Networks
networks:
  curr_rate_network:
    driver: bridge
volumes:
  dbdata:
    driver: local
